// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnrcoyypgPXyPMcP80uYKgrn3ll4n9Xtk',
    appId: '1:957430701914:web:4adece965eb0e689fd5d63',
    messagingSenderId: '957430701914',
    projectId: 'kisanmitra-b9790',
    authDomain: 'kisanmitra-b9790.firebaseapp.com',
    storageBucket: 'kisanmitra-b9790.firebasestorage.app',
    measurementId: 'G-MYTRWDY8V4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8ahep-vnWzyQlxl3x1lJ9Ws98OC_KKwI',
    appId: '1:957430701914:android:b195bc268ff4d987fd5d63',
    messagingSenderId: '957430701914',
    projectId: 'kisanmitra-b9790',
    storageBucket: 'kisanmitra-b9790.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnrcoyypgPXyPMcP80uYKgrn3ll4n9Xtk',
    appId: '1:957430701914:web:77b3adc172c832ebfd5d63',
    messagingSenderId: '957430701914',
    projectId: 'kisanmitra-b9790',
    authDomain: 'kisanmitra-b9790.firebaseapp.com',
    storageBucket: 'kisanmitra-b9790.firebasestorage.app',
    measurementId: 'G-T1ZNVCP7Q3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnOBxGyx0oK69PbmpoR6YfAmsofzdN7nM',
    appId: '1:957430701914:ios:9f017fe0cb8d3144fd5d63',
    messagingSenderId: '957430701914',
    projectId: 'kisanmitra-b9790',
    storageBucket: 'kisanmitra-b9790.firebasestorage.app',
    iosBundleId: 'com.kisanmitra.kisanMitra',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnOBxGyx0oK69PbmpoR6YfAmsofzdN7nM',
    appId: '1:957430701914:ios:9f017fe0cb8d3144fd5d63',
    messagingSenderId: '957430701914',
    projectId: 'kisanmitra-b9790',
    storageBucket: 'kisanmitra-b9790.firebasestorage.app',
    iosBundleId: 'com.kisanmitra.kisanMitra',
  );

}