from selenium.webdriver.common.by import By
from pages.base_page import BasePage
import time

class DiseaseScanPage(BasePage):
    UPLOAD_PLACEHOLDER = (By.XPATH, "//*[text()='Upload Leaf Photo'] | //flt-semantics[contains(@aria-label, 'Upload Leaf')]")
    FILE_INPUT = (By.XPATH, "//input[@type='file']")
    START_ANALYSIS_BUTTON = (By.XPATH, "//*[text()='Start AI Analysis'] | //flt-semantics[contains(@aria-label, 'Analysis')]")
    
    # Result elements
    DETECTION_RESULT_HEADER = (By.XPATH, "//*[contains(text(), 'Detection Result')] | //flt-semantics[contains(@aria-label, 'Result')] | //flt-semantics[contains(@aria-label, 'CROP TYPE')]")
    DISEASE_NAME_ELEMENT = (By.XPATH, "//flt-semantics[contains(@aria-label, 'Disease')] | //flt-semantics[contains(@aria-label, 'healthy')]")

    def upload_leaf_image(self, file_path):
        """Mocks picking an image by sending the file path directly to the hidden input."""
        # Click placeholder to trigger input appending if needed (in some implementations)
        # Flutter's image picker web injects the input dynamically. Sometimes it requires a click,
        # but often it's appended on request. Let's make it robust by trying to click the upload placeholder.
        try:
            self.click(self.UPLOAD_PLACEHOLDER)
            time.sleep(1)
        except Exception:
            pass
        
        # Locate the dynamically created file input and type the file path
        input_el = self.wait_for_element(self.FILE_INPUT)
        # HTML input elements generated by Flutter web image_picker might be hidden.
        # We can write keys directly to them using standard selenium send_keys.
        input_el.send_keys(file_path)
        time.sleep(2)

    def start_analysis(self):
        """Click the Start AI Analysis button."""
        self.click(self.START_ANALYSIS_BUTTON)

    def is_result_displayed(self, timeout=20):
        """Wait for result header to appear."""
        try:
            WebDriverWait(self.driver, timeout).until(
                EC.visibility_of_element_located(self.DETECTION_RESULT_HEADER)
            )
            return True
        except Exception:
            return False

    def get_diagnosis(self):
        """Retrieve diagnosed plant/disease text from result headers."""
        try:
            header_el = self.wait_for_element(self.DETECTION_RESULT_HEADER)
            return header_el.text or header_el.get_attribute("aria-label") or ""
        except Exception:
            return ""
